create extension if not exists pgcrypto;

create table if not exists public.cards (
    id uuid primary key default gen_random_uuid(),
    poketrace_id text not null unique,
    name text not null,
    card_number text,
    set_name text,
    set_slug text,
    variant text,
    rarity text,
    image_url text,
    tcgplayer_id text,
    marketplace_urls jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.collection_items (
    id uuid primary key default gen_random_uuid(),
    card_id uuid not null references public.cards(id) on delete cascade,
    quantity integer not null default 1 check (quantity > 0),
    ownership_grade text not null default 'RAW'
        check (ownership_grade in ('RAW', 'PSA_7', 'PSA_8', 'PSA_9', 'PSA_10')),
    purchase_price numeric(12, 2),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.price_snapshots (
    id bigint generated by default as identity primary key,
    card_id uuid not null references public.cards(id) on delete cascade,
    grade text not null
        check (grade in ('RAW', 'PSA_7', 'PSA_8', 'PSA_9', 'PSA_10')),
    source text not null,
    value numeric(12, 2) not null check (value >= 0),
    source_url text,
    observed_at timestamptz not null default now(),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_collection_items_card_id
    on public.collection_items(card_id);

create index if not exists idx_price_snapshots_card_grade_observed
    on public.price_snapshots(card_id, grade, observed_at desc);

create index if not exists idx_price_snapshots_card_source_grade
    on public.price_snapshots(card_id, source, grade);

alter table public.cards enable row level security;
alter table public.collection_items enable row level security;
alter table public.price_snapshots enable row level security;

-- Intentionally no public RLS policies.
-- The React frontend never talks directly to Supabase.
-- The FastAPI backend uses the server-only Supabase secret key.

-- Small key/value store for state that has to survive a hosted backend
-- sleeping or redeploying (TCGGO daily quota, sync cooldown).
create table if not exists public.app_state (
    key text primary key,
    value jsonb not null,
    updated_at timestamptz not null default now()
);

alter table public.app_state enable row level security;

-- Collection history: one row per card added to or removed from the
-- collection, with the market value it entered or left at. The dashboard's
-- performance chart subtracts these flows so adding or removing cards never
-- shows up as a gain or loss - only price movement does.
create table if not exists public.collection_events (
    id bigint generated by default as identity primary key,
    -- The collection_items row (the "lot") this event belongs to. No foreign
    -- key on purpose: the history must outlive the row once a lot is fully
    -- removed.
    collection_item_id uuid not null,
    card_id uuid not null references public.cards(id) on delete cascade,
    grade text not null
        check (grade in ('RAW', 'PSA_7', 'PSA_8', 'PSA_9', 'PSA_10')),
    event_type text not null check (event_type in ('ADD', 'REMOVE')),
    quantity integer not null check (quantity > 0),
    -- Market value per card when the event was recorded (null if the card had
    -- no price yet, or the event was backfilled). REMOVE flows are negative.
    market_value_per_card numeric(12, 2),
    total_flow_value numeric(12, 2),
    occurred_at timestamptz not null,
    recorded_by text not null default 'app'
        check (recorded_by in ('app', 'backfill')),
    created_at timestamptz not null default now()
);

create unique index if not exists idx_collection_events_one_add_per_item
    on public.collection_events(collection_item_id)
    where event_type = 'ADD';

create index if not exists idx_collection_events_occurred
    on public.collection_events(occurred_at, id);

alter table public.collection_events enable row level security;

-- Backfill: every card already in the collection gets an ADD event at the
-- moment it was added. Market values weren't recorded back then, so they stay
-- null and the backend values them from price history. Safe to re-run.
insert into public.collection_events
    (collection_item_id, card_id, grade, event_type, quantity, occurred_at, recorded_by)
select ci.id, ci.card_id, ci.ownership_grade, 'ADD', ci.quantity, ci.created_at, 'backfill'
from public.collection_items ci
where not exists (
    select 1
    from public.collection_events e
    where e.collection_item_id = ci.id
      and e.event_type = 'ADD'
);
