create extension if not exists pgcrypto;

create table if not exists public.cards (
    id uuid primary key default gen_random_uuid(),
    poketrace_id text not null unique,
    name text not null,
    card_number text,
    set_name text,
    set_slug text,
    variant text,
    rarity text,
    image_url text,
    tcgplayer_id text,
    marketplace_urls jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.collection_items (
    id uuid primary key default gen_random_uuid(),
    card_id uuid not null references public.cards(id) on delete cascade,
    quantity integer not null default 1 check (quantity > 0),
    ownership_grade text not null default 'RAW'
        check (ownership_grade in ('RAW', 'PSA_7', 'PSA_8', 'PSA_9', 'PSA_10')),
    purchase_price numeric(12, 2),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.price_snapshots (
    id bigint generated by default as identity primary key,
    card_id uuid not null references public.cards(id) on delete cascade,
    grade text not null
        check (grade in ('RAW', 'PSA_7', 'PSA_8', 'PSA_9', 'PSA_10')),
    source text not null,
    value numeric(12, 2) not null check (value >= 0),
    source_url text,
    observed_at timestamptz not null default now(),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_collection_items_card_id
    on public.collection_items(card_id);

create index if not exists idx_price_snapshots_card_grade_observed
    on public.price_snapshots(card_id, grade, observed_at desc);

create index if not exists idx_price_snapshots_card_source_grade
    on public.price_snapshots(card_id, source, grade);

alter table public.cards enable row level security;
alter table public.collection_items enable row level security;
alter table public.price_snapshots enable row level security;

-- Intentionally no public RLS policies.
-- The React frontend never talks directly to Supabase.
-- The FastAPI backend uses the server-only Supabase secret key.

-- Small key/value store for state that has to survive a hosted backend
-- sleeping or redeploying (TCGGO daily quota, sync cooldown).
create table if not exists public.app_state (
    key text primary key,
    value jsonb not null,
    updated_at timestamptz not null default now()
);

alter table public.app_state enable row level security;
